[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
trustscore = "BAoYiH6vNDCvZgggccAisSNRtCCtDDnzWkfU2Hu3SmEb"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "./wallet_1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
